apiVersion: v1
kind: Namespace
metadata:
  name: wetty
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wetty-init-script
  namespace: wetty
data:
  init-certs.sh: |
    #!/bin/sh
    if [ ! -f /etc/wetty/key.pem ]; then
      apk add --no-cache openssl
      openssl req -x509 -newkey rsa:4096 \
        -keyout /etc/wetty/key.pem \
        -out /etc/wetty/cert.pem \
        -sha256 -days 3650 -nodes \
        -subj "/O=Portworx"
      echo "Certificates generated"
    else
      echo "Certificates already exist"
    fi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wetty-cert-generator
  namespace: wetty
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      restartPolicy: OnFailure
      containers:
      - name: cert-generator
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
        image: alpine:latest
        command: ["/bin/sh", "/scripts/init-certs.sh"]
        volumeMounts:
        - name: wetty-certs
          mountPath: /etc/wetty
        - name: init-script
          mountPath: /scripts
      volumes:
      - name: wetty-certs
        hostPath:
          path: /etc/wetty
      - name: init-script
        configMap:
          name: wetty-init-script
          defaultMode: 0755
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetty
  namespace: wetty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wetty
  template:
    metadata:
      labels:
        app: wetty
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: wetty
        image: wettyoss/wetty:latest
        args:
          - "-p"
          - "443"
          - "--ssl-key"
          - "/etc/wetty/key.pem"
          - "--ssl-cert"
          - "/etc/wetty/cert.pem"
          - "--force-ssh"
        ports:
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        volumeMounts:
        - name: wetty-certs
          mountPath: /etc/wetty
          readOnly: true
        securityContext:
          capabilities:
            add:
              - NET_BIND_SERVICE
      volumes:
      - name: wetty-certs
        hostPath:
          path: /etc/wetty
