kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: redis
  name: redis-data
spec:
  storageClassName: px-csi-db
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:8.2.3
        args: ["--requirepass", "$(REDIS_PASS)"]
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_PASS
          value: password
        volumeMounts:
        - name: redis-vol
          mountPath: /data
        lifecycle:
          postStart:
            exec:
              command: ["chown", "redis:redis", "/data"]
      volumes:
      - name: redis-vol
        persistentVolumeClaim:
          claimName: redis-data
