description: Deploys training clusters
scripts: ["training-cluster"]
px_version: 3.4.0.1
k8s_version: 1.33.5
stop_after: 0
cluster:
  - id: 1
    scripts: ["etcd", "wetty", "snoop", "training-bastion"]
